### ISSUE TITLE
Update `pipeline_type` options and default in `ecephys.run_sorting()`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-session#13]
@alejoe91 changed the accepted parameters and not backwards compatible

**Comment by alejoe91** [comment]
Will add it back for backward compatibility!

**Comment by alejoe91** [comment]
@bjhardcastle I added the old behavior. It will convert `ecephys` to `ecephys_ks25` (default pipelin)

**Comment by bjhardcastle** [comment]
@alejoe91 thanks! And I'll update the listed options here going forward.
