### ISSUE TITLE
question: installation with pip slow

### ISSUE THREAD

**Issue by mattjdavis** [AllenNeuralDynamics/aind-session#5]
running `pip install aind-session` in a new capsule (py3.9 image) is very very slow to build. Lots of waiting for pips dependency resolver.

In another capsule I tried installing pdm, cloning the repo and then using `pdm install`; the capsule built fine. But that failed when I tried to `import aind_session` in the python environment. 

Any tips?

**Comment by bjhardcastle** [comment]
Hey, sorry for the slow reply.

I'm seeing the same thing: the main culprits seem to be "annotated-types" (pydantic dependency) and "python-dateutil" (botocore dependency). Mine has been resolving for >20 minutes so I'll try restricting versions of specific packages for the sake of getting it to install faster.

pdm might have created a .venv folder in the same directory as the cloned repo, in which case you'd just need to activate that with something like `source /code/aind-session/.venv/bin/activate` 
I've not tried using pdm to develop in a capsule though - maybe we can meet and try to figure it out.

**Comment by bjhardcastle** [comment]
@mattjdavis it should now take a reasonable amount of time to pip install with the latest version (0.1.20)
